### ISSUE TITLE
error message: ** (MatchError) no match of right hand side value: {:error, :closed}

### ISSUE THREAD

**Issue by dapperAuteur** [josevalim/kv_umbrella#2]
I got this error message on my tests. It started appearing at the of the doctests section of the tutorial. Here's the response in terminal:
```
1) test server interaction (KVServerTest)
     test/kv_server_test.exs:23
     ** (MatchError) no match of right hand side value: {:error, :closed}
     code: assert send_and_recv(socket, "GET shopping eggs\r\n") == "NOT FOUND\r\n"
     stacktrace:
       test/kv_server_test.exs:45: KVServerTest.send_and_recv/2
       test/kv_server_test.exs:26: (test)

     The following output was logged:

     15:30:43.266 [info]  Application kv exited: :stopped

     15:30:43.305 [error] Task #PID<0.258.0> started from #PID<0.138.0> terminating
     ** (UndefinedFunctionError) function KVServer.Command.run/1 is undefined or private. Did you mean one of:

           * run/2

         (kv_server) KVServer.Command.run({:get, "shopping", "eggs"})
         (kv_server) lib/kv_server.ex:55: KVServer.serve/1
         (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
         (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
     Function: #Function<0.83028181/0 in KVServer.loop_acceptor/1>
         Args: []
```

[files.zip](https://github.com/josevalim/kv_umbrella/files/1304884/files.zip)

**Comment by josevalim** [comment]
The error says the KVServer.Command.run/1 function is not defined. But you haven't sent such file. Can you please make sure this module is defined in lib, as shown here? https://github.com/josevalim/kv_umbrella/blob/master/apps/kv_server/lib/kv_server/command.ex

**Comment by dapperAuteur** [comment]
Thank you for your help. I'll compare my command.ex file to yours. This is my lib/kv_server/command.ex file:
```
defmodule KVServer.Command do
  @doc ~s"""
  Parses the given `line` into a command.

  ## Examples

  iex> KVServer.Command.parse "CREATE shopping\\r\\n"
  {:ok, {:create, "shopping"}}

  iex> KVServer.Command.parse "CREATE shopping\\r\\n"
  {:ok, {:create, "shopping"}}

  iex> KVServer.Command.parse "PUT shopping milk 1\\r\\n"
  {:ok, {:put, "shopping", "milk", "1"}}

  iex> KVServer.Command.parse "GET shopping milk\\r\\n"
  {:ok, {:get, "shopping", "milk"}}

  iex> KVServer.Command.parse "DELETE shopping eggs\\r\\n"
  {:ok, {:delete, "shopping", "eggs"}}

  Unkown commands or commands with the wrong number of arguments return an error:

  iex> KVServer.Command.parse "UNKNOWN shopping eggs\\r\\n"
  {:error, :unknown_command}

  iex> KVServer.Command.parse "GET shopping\\r\\n"
  {:error, :unknown_command}

  iex> 1 + 1
  2

  iex> Enum.map [1, 2, 3], fn(x) ->
  ...> x * 2
  ...> end
  [2, 4, 6]

  iex> Enum.map [1, 2, 3], fn(x) ->
  iex> x + 3
  iex> end
  [4, 5, 6]

  iex> a = 1
  1
  iex> a + 1
  2

  iex> pid = spawn fn -> :ok end
  iex> is_pid(pid)
  true

  iex(1)> [1 + 2,
  ...(1)> 3]
  [3, 3]

  iex(1)> [3 -1,
  iex(1)> 4]
  [2, 4]
  """

  # def parse(_line) do
  #   :not_implemented
  # end

  def parse(line) do
    case String.split(line) do
      ["CREATE", bucket] -> {:ok, {:create, bucket}}
      ["GET", bucket, key] -> {:ok, {:get, bucket, key}}
      ["PUT", bucket, key, value] -> {:ok, {:put, bucket, key, value}}
      ["DELETE", bucket, key] -> {:ok, {:delete, bucket, key}}
      _ -> {:error, :unknown_command}
    end
  end

  @doc """
  Runs the given command.
  """
  def run(command)

  def run({:create, bucket}, pid) do
    KV.Registry.create(pid, bucket)
    {:ok, "OK\r\n"}
  end

  def run({:get, bucket, key}, pid) do
    lookup bucket, fn pid ->
      value = KV.Bucket.get(pid, key)
      {:ok, "#{value}\r\nOK\r\n"}
    end
  end

  def run({:put, bucket, key, value}, pid) do
    lookup bucket, fn pid ->
      KV.Bucket.put(pid, key, value)
      {:ok, "OK\r\n"}
    end
  end

  def run({:delete, bucket, key}, pid) do
    lookup bucket, fn pid ->
      KV.Bucket.delete(pid, key)
      {:ok, "OK\r\n"}
    end
  end

  defp lookup(bucket, callback) do
    case KV.Registry.lookup(KV.Registry, bucket) do
      {:ok, pid} -> callback.(pid)
      :error -> {:error, :not_found}
    end
  end
end
```

**Comment by josevalim** [comment]
Can you upload your whole application somewhere so I can try it out?

**Comment by dapperAuteur** [comment]
https://github.com/dapperAuteur/elixir-lang-kv-tutorial
the distributed branch is the branch I'm on. Thank you.

**Comment by josevalim** [comment]
@dapperAuteur I get a different error than the one you posted:

```

  1) test server interaction (KVServerTest)
     test/kv_server_test.exs:23
     Assertion with == failed
     code:  assert send_and_recv(socket, "GET shopping eggs\r\n") == "NOT FOUND\r\n"
     left:  "ERROR\r\n"
     right: "NOT FOUND\r\n"
     stacktrace:
       test/kv_server_test.exs:26: (test)

     The following output was logged:

     18:01:45.911 [info]  Application kv exited: :stopped

     18:01:45.920 [error] Task #PID<0.268.0> started from #PID<0.136.0> terminating
     ** (stop) :not_found
         (kv_server) lib/kv_server.ex:83: KVServer.write_line/2
         (kv_server) lib/kv_server.ex:56: KVServer.serve/1
         (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
         (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
     Function: #Function<0.130391324/0 in KVServer.loop_acceptor/1>
         Args: []
```

Can you confirm you are getting the same?

**Comment by josevalim** [comment]
Btw, the compiler is telling you what is wrong with your code. It says this:

```
warning: this clause cannot match because a previous clause at line 80 always matches
  lib/kv_server.ex:86
```

Line 80 is this:

```
  defp write_line(socket, {:error, error}) do
    # Unknown error. Write to the client and exit.
    :gen_tcp.send(socket, "ERROR\r\n")
    exit(error)
  end
```

Line 86 is this:

```
  defp write_line(socket, {:error, :not_found}) do
    :gen_tcp.send(socket, "NOT FOUND\r\n")
  end
```

Line 86 won't ever match because line 80 is already matching on all errors. If you reverse them, the test progresses (until the next error).

Maybe there is something in the tutorial that could be clearer?

**Comment by dapperAuteur** [comment]
I'm getting that error now too. I was getting the other error before the most recent push. I changed my code after reviewing the command.ex file you shared. I had a few errors. I had ```@doc ~s``` and not ```@doc ~S```. Then I removed the escape character ('\') from the ```\\r\\n``` and now it reads ```\r\n```. I'll review the tutorial regarding the new error. Thank you.

**Comment by dapperAuteur** [comment]
Thank you again for your help. It was an ID-10T error.
I found it. I was missing an ')'. It was in the wrong place.
this is what I had.
```
# # GET returns two lines
    # This test is the error
    assert send_and_recv(socket, "GET shopping eggs\r\n") == "3\r\n"
    assert send_and_recv(socket, "" == "OK\r\n")
```
is the correct version:
```
# # GET returns two lines
    # This test is the error
    assert send_and_recv(socket, "GET shopping eggs\r\n") == "3\r\n"
    assert send_and_recv(socket, "") == "OK\r\n"
```
